FROM python:3.11.5

WORKDIR /app
COPY . /app

COPY ./requirements.txt .
#RUN pip install fastapi uvicorn[standard] --no-cache-dir
RUN pip install --no-cache-dir -r requirements.txt
RUN wget https://github.com/jwilder/dockerize/releases/download/v0.6.1/dockerize-linux-amd64-v0.6.1.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-v0.6.1.tar.gz
RUN pip install cryptography

ENV PYTHONPATH=/backend

ENTRYPOINT ["dockerize", "-wait", "tcp://db:3306", "-timeout", "20s"]
CMD ["uvicorn","main:app","--host","0.0.0.0","--port","80", "--reload"]